apiVersion: v1
kind: Service
metadata:
  name: performance-sandbox
  labels:
    app: performance-sandbox
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
spec:
  type: NodePort
  selector:
    app: performance-sandbox
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
