prometheus-adapter:
  dnsPolicy: ClusterFirstWithHostNet
  logLevel: 10
  prometheus:
    url: 'http://performance-sandbox-prometheus-server'
    port: 80
  rules:
    default: false
    custom:
      - seriesQuery: 'kube_pod_container_status_ready{container = "performance-sandbox", pod =~"performance-sandbox-deployment.*", namespace != ""}'
        resources:
          overrides:
            pod: {resource: "pod"}
            namespace: {resource: "namespace"}
        metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>)
metrics-server:
  args:
    - --kubelet-insecure-tls
    - --kubelet-preferred-address-types=InternalIP
