prometheus-adapter:
  dnsPolicy: ClusterFirstWithHostNet
  prometheus:
    url: 'http://performance-sandbox-prometheus-server'
    port: 80
  rules:
    default: false
    custom:
      - seriesQuery: '{__name__=~"^queue_ratio$"}'
        resources:
          overrides:
            kubernetes_pod_name:
              resource: pod
            kubernetes_namespace:
              resource: namespace
        name:
          matches: ''
          as: 'queue_ratio'
        metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>)
metrics-server:
  args:
    - --kubelet-insecure-tls
    - --kubelet-preferred-address-types=InternalIP
